language: java
#dist: trusty
#jdk: openjdk8
jdk: oraclejdk8
install:
- git clone --depth=1 --branch=master https://github.com/servicecatalog/service-tools.git
  servicecatalog/service-tools
- cd servicecatalog/service-tools
- mvn install -f ./oscm-common-build/pom.xml
- cd ../..
script:
- mvn install cobertura:cobertura -f ./oscm-provisioning-build/pom.xml
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
after_success:
  #- bash <(curl -s https://codecov.io/bash
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - export REPO=servicecatalog/provisioning-service
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
